sudo: required

language: java

addons:
    hosts:
      - db

jdk:
  - openjdk11

services:
  - docker

install:
  - mvn clean install -DskipTests=true -D"maven.javadoc.skip=true" -B -V

jobs:
  include:
    - stage: Units
      install: skip
      script: mvn test -Dtest="com.napier.group20.places.*Test"
    - stage: Integration
      script:
        - sudo docker-compose up -d db
        - mvn test -Dtest="com.napier.group20.utils.*Test"
    - stage: GitHub Release
      install: skip
      script: mvn package -DskipTests=true -D"maven.javadoc.skip=true"
      before_deploy:
        - git config --local user.name "glugg23"
        - git config --local user.email "m.leonhardt424@gmail.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $TRAVIS_BUILD_DIR/target/SET08103-G20.jar
        skip_cleanup: true

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

stages:
  - Units
  - Integration
  - name: GitHub Release
    if: branch = master
