sudo: required

language: java

jdk:
  - oraclejdk11
  - openjdk11

services:
  - docker

after_success:
  - mvn install
  - sudo systemctl stop mariadb
  - sudo systemctl stop mysql
  - sudo docker-compose up --build
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
