sudo: required

language: java

addons:
    hosts:
      - db

jdk:
  - oraclejdk11
  - openjdk11

services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker-compose up --build --abort-on-container-exit

jobs:
  include:
    - stage: Units
      install: skip
      jdk: openjdk11
      script: mvn test -Dtest="com.napier.group20.places.*Test"
    - stage: Integration
      jdk: openjdk11
      script: echo "Integration insert here"
    - stage: Deployment
      install: skip
      jdk: openjdk11
      script: echo "Deployment insert here"

before_script:
  - mvn clean
  - service mariadb stop
  - service mysql stop
  - service postgresql stop

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
