#docker-compose up --build --abort-on-container-exit (sudo if daemon is superuser)
#if any issues are encountered, it is recommended you run docker_rm.sh
#-> and stop any mysql services that use the port 3306.
version: '3.3'
services:
  db:
    build: src/main/resources/
    restart: always

  app:
    build: .
    links:
      - db
