#docker-compose up --build --abort-on-container-exit (sudo if daemon is superuser)
#if any issues are encountered, it is recommended you run docker_rm.sh
#-> and stop any mysql services that use the port 3306.
version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: world
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./src/main/resources/:/docker-entrypoint-initdb.d/

  app:
    build: .
    links:
      - db
