#docker-compose up --build
version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: world
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-psecret"]
      timeout: 5s
      retries: 10
  app:
    build: .
    depends_on:
      - db
    links:
      - db
