@startuml
left to right direction

rectangle "World Database" as S2

:Population Analyst: as A1
:Statistician: as A2

rectangle "Query System" as S1 {
    (Print report to user display) as U1
    (Display the number of people in the world\n and the % who speak each language) as U2
    A1 -- U2
    (Displaying name of selected area, its total population\n the percentage of people living in cities and\n not living in cities.) as U3
    A2 -- U3
    (Displaying countries organised by population in \nterms of continents, regions, and the world.) as U4
    A1 -- U4
    (Return the top N populated countries in the\n world, continent and region.) as U5
    A1 -- U5
    (Return the top N populated cities from \nthe world, continents,\n regions, countries and districts) as U6
    A1 -- U6
    (Display a list of all the capital cities in \nthe world, continent or region\n, organised by largest to smallest) as U7
    A1 -- U7
    (Return the top n populated capital cities from the world, continents, regions, countries and districts) as U8
    A1 -- U8
    (Displaying a list of all cities order by population with associated metadata) as U9
    A1 -- U9
    (Displaying the total population of people living in cities and not) as U10
    A2 -- U10


    A1 ..> U5 : " inputs N"
    A1 ..> U6 : " inputs N"
    A1 ..> U8 : " input N"
    U2 ..> U1 : " include"
    U3 ..> U1 : " include"
    U4 ..> U1 : " include"
    U5 ..> U1 : " include"
    U6 ..> U1 : " include"
    U7 ..> U1 : " include"
    U8 ..> U1 : " include"
    U9 ..> U1 : " include"
    U10 ..> U1 : " include"

    U2 -left- S2
    U3 -left- S2
    U4 -left- S2
    U5 -left- S2
    U6 -left- S2
    U7 -left- S2
    U8 -left- S2
    U9 -left- S2
    U10 -left- S2
}

@enduml
